# Generated by Django 5.1.7 on 2025-09-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='code',
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='companies',
            field=models.JSONField(blank=True, default=list, help_text='Example: ["Amazon", "Flipkart"]'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Example: ["Array", "Math"]'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('docker_image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name', 'version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Compilation Error', 'Compilation Error'), ('Runtime Error', 'Runtime Error'), ('TLE', 'TLE')], default='In Progress', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_output', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('time_taken', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Failed', 'Failed')], max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='coding.submission')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.testcase')),
            ],
            options={
                'db_table': 'submission_logs',
                'ordering': ['submission', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_solution', to='coding.codingquestion')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.language')),
            ],
            options={
                'verbose_name': 'Coding Solution',
                'verbose_name_plural': 'Coding Solutions',
                'db_table': 'coding_solution',
                'ordering': ['-created_at'],
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'question'], name='submissions_user_id_50aaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionlog',
            index=models.Index(fields=['submission', 'testcase'], name='submission__submiss_7b7485_idx'),
        ),
    ]
