# Generated by Django 5.1.7 on 2025-09-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_remove_codingquestion_code_codingquestion_metadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionlog',
            options={'ordering': ['submission', 'testcase']},
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='message',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='submissionlog',
            unique_together={('submission', 'testcase')},
        ),
    ]
