# Generated by Django 5.1.7 on 2025-09-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0002_question_description_question_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='description_right_options_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
    ]
