# Generated by Django 5.1.7 on 2025-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='job_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
