# Generated by Django 5.1.7 on 2025-11-22 05:35

import interviewsathi.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewsession_job_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpdf',
            name='pdf_file',
            field=models.FileField(storage=interviewsathi.storage_backends.PrivateMediaStorage(), upload_to='question_pdfs/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=interviewsathi.storage_backends.PrivateMediaStorage(), upload_to='resumes/'),
        ),
    ]
