# Generated by Django 5.1.7 on 2025-11-22 05:35

import interviewsathi.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, storage=interviewsathi.storage_backends.PublicMediaStorage(), upload_to='avatars/'),
        ),
    ]
