# Generated by Django 5.1.7 on 2025-11-27 12:38

import django.db.models.deletion
import interviewsathi.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=interviewsathi.storage_backends.PrivateMediaStorage(), upload_to='resumes/')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('is_valid_resume', models.BooleanField(default=False)),
                ('matches_user', models.BooleanField(default=False)),
                ('is_deteted', models.BooleanField(default=False)),
                ('parsed_text', models.TextField(blank=True)),
                ('parsed_json', models.JSONField(blank=True, default=dict, null=True)),
                ('lambda_raw', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'resume',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
