# Generated by Django 5.1.7 on 2025-11-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='is_deteted',
            new_name='is_deleted',
        ),
    ]
