# Generated by Django 5.1.7 on 2025-11-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_is_deteted_resume_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
